name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/general.*